kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: my-nodejs
          image: nodejs-image:latest
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-nodejs-svc
spec:
  ports:
    - name: http-8090
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: nodejs-app